# Generated by Django 4.2.7 on 2024-05-20 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(null=True, unique=True)),
                ('kor_co_nm', models.TextField(null=True)),
                ('fin_prdt_nm', models.TextField(null=True)),
                ('etc_note', models.TextField(null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('join_member', models.TextField(null=True)),
                ('join_way', models.TextField(null=True)),
                ('spcl_cnd', models.TextField(null=True)),
                ('dcls_month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(null=True, unique=True)),
                ('kor_co_nm', models.TextField(null=True)),
                ('fin_prdt_nm', models.TextField(null=True)),
                ('etc_note', models.TextField(null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('join_member', models.TextField(null=True)),
                ('join_way', models.TextField(null=True)),
                ('spcl_cnd', models.TextField(null=True)),
                ('dcls_month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField(blank=True, default=-1)),
                ('intr_rate2', models.FloatField(blank=True, default=-1)),
                ('save_trm', models.IntegerField()),
                ('saving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.saving')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField(blank=True, default=-1)),
                ('intr_rate2', models.FloatField(blank=True, default=-1)),
                ('save_trm', models.IntegerField()),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.deposit')),
            ],
        ),
    ]
