# Generated by Django 4.2.4 on 2024-05-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('cur_unit', models.CharField(max_length=10)),
                ('cur_nm', models.CharField(max_length=50)),
                ('ttb', models.CharField(max_length=20)),
                ('tts', models.CharField(max_length=20)),
                ('deal_bas_r', models.CharField(max_length=20)),
                ('bkpr', models.CharField(max_length=20)),
                ('yy_efee_r', models.CharField(max_length=20)),
                ('ten_dd_efee_r', models.CharField(max_length=20)),
                ('kftc_deal_bas_r', models.CharField(max_length=20)),
                ('kftc_bkpr', models.CharField(max_length=20)),
            ],
        ),
    ]
